# Generated by Django 4.1.1 on 2022-10-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0003_usersrecord_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersrecord',
            name='category',
        ),
        migrations.AddField(
            model_name='usersrecord',
            name='category',
            field=models.ManyToManyField(to='notebook.category'),
        ),
    ]
