# Generated by Django 4.1.1 on 2022-10-03 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0004_remove_usersrecord_category_usersrecord_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersRecord',
            new_name='User',
        ),
    ]
