# Generated by Django 4.1.1 on 2022-10-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0007_userrecord_remove_category_user_delete_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='category',
        ),
        migrations.AddField(
            model_name='userrecord',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.category'),
        ),
    ]
