# Generated by Django 4.1.1 on 2022-10-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0009_usercategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercategory',
            options={'verbose_name': 'User category', 'verbose_name_plural': 'User categories'},
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ManyToManyField(to='notebook.category'),
        ),
    ]
