# Generated by Django 4.1.1 on 2022-10-04 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0011_profilis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilis',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nuotrauka',
            new_name='photo',
        ),
    ]
