# Generated by Django 4.1.1 on 2022-10-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0013_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
