# Generated by Django 4.1.1 on 2022-10-05 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notebook', '0014_remove_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrecord',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='record',
        ),
        migrations.RemoveField(
            model_name='userrecord',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserCategory',
        ),
        migrations.DeleteModel(
            name='UserRecord',
        ),
    ]
