# Generated by Django 4.1.1 on 2022-10-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0016_record_image_alter_category_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='category',
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='notebook.category'),
            preserve_default=False,
        ),
    ]
